site_name: PMYning
site_url: https://willembressers.github.io/pmyning

theme:
  name: readthedocs

plugins:
  - search
  - gen-files:
      scripts:
      - scripts/gen_pages.py
  - literate-nav:
      nav_file: SUMMARY.md
  - mkdocstrings

nav:
  - Home: index.md
  - API: pmyning/
  - Development: development.md
  - About: about.md